### ISSUE TITLE
Error: Internal Error: Calculate hash value for sources

### ISSUE THREAD

**Issue by MrChico** [seppeljordan/nix-prefetch-github#31] opened 2019-12-30 21:01 UTC
This project suddently stopped working on my macos. I'm getting the following error regardless of which repo I choose as argument:
```sh
nix-prefetch-github seppeljordan nix-prefetch-github
Error: Internal Error: Calculate hash value for sources in github repo seppeljordan/nix-prefetch-github.
```

I'm using
``` 
nix-prefetch-github --version
nix-prefetch-github, version 2.3.2
```

It used to work. Not sure what's going on..

**Comment by seppeljordan** [comment] 2020-02-16 13:25
Hi,

thanks for reporting this issue.  Does the issue persist?  Which version of nixpkgs are you on?

Cheers

**Comment by 06kellyjac** [comment] 2020-04-29 13:57
`nix-prefetch-github, version 2.3.2`

`nixos https://nixos.org/channels/nixos-unstable`

```
λ nix-prefetch-github "seppeljordan" "nix-prefetch-github"
Error: Internal Error: Calculate hash value for sources in github repo seppeljordan/nix-prefetch-github.
```
exit code `1`

**Comment by poscat0x04** [comment] 2020-07-02 08:37
Hi, I bumped into this as well, prefetch with revision does not work at all.

**Comment by jtojnar** [comment] 2020-07-08 18:06
For me this issue seems to be caused by removing `nixpkgs` from `NIX_PATH`, since it is required by the fetcher:

https://github.com/seppeljordan/nix-prefetch-github/blob/dc3e2fd38a8f1844702937d01b910aab69738976/src/nix_prefetch_github/templates/prefetch-github.nix.j2#L2

**Comment by seppeljordan** [comment] 2020-07-20 17:27
I am closing this since OP is not responding. Please open separate issues if you still have problems. Also make sure that you install the latest version of nix-prefetch-github which is 2.4 as of writing this comment.

**Closed by seppeljordan** 2020-07-20 17:27 UTC

**Comment by MrChico** [comment] 2020-07-20 17:31
Sorry for not responding. FWIW this issue stopped occuring for me so I have not been able to provide more info :+1:

**Comment by seppeljordan** [comment] 2020-07-20 17:49
Sounds like a happy end to me :) no worries
